remote_theme: pages-themes/hacker@v0.2.0

plugins:
  - jekyll-remote-theme

title: Popular Bangladeshi Landmarks Recognizer
description: An image classification API that classifies 16 different types of landmarks of Bangladesh
author: Fahim Faiyaz
